from __future__ import annotations

from typing import List

from .models import AutomationModule


def catalog() -> List[AutomationModule]:
    return [
        AutomationModule(
            name="Bot de ventas para WhatsApp",
            description="Captura leads, responde FAQs, califica prospectos y agenda llamadas.",
            effort="M",
            impact=5,
            integrations=["WhatsApp", "CRM"],
            estimated_weeks=3,
            tags=["whatsapp", "ventas", "leads", "seguimiento", "cotizacion", "citas", "agenda", "reservas"],
        ),
        AutomationModule(
            name="Eficiencia administrativa (archivos y carpetas)",
            description="Estandariza y automatiza carpetas, archivos y organizacion documental en la nube (0 caos, 0 perdida de info).",
            effort="M",
            impact=5,
            integrations=["Google Drive", "OneDrive", "Dropbox"],
            estimated_weeks=2,
            tags=[
                "carpetas",
                "carpeta",
                "archivos",
                "archivo",
                "drive",
                "onedrive",
                "dropbox",
                "documentos",
                "documento",
                "organizar",
                "organizacion",
                "papeleo",
                "papel",
            ],
        ),
        AutomationModule(
            name="Generador de documentos inteligente",
            description="Crea automaticamente facturas, contratos, cotizaciones y recibos en PDF desde cualquier disparador.",
            effort="L",
            impact=5,
            integrations=["PDF", "Drive", "Correo", "ERP", "Firma"],
            estimated_weeks=3,
            tags=[
                "factura",
                "facturacion",
                "contrato",
                "cotizacion",
                "cotizar",
                "pdf",
                "recibo",
                "firma",
                "firmar",
                "documento",
                "documentos",
            ],
        ),
        AutomationModule(
            name="Chatbot de atencion al cliente",
            description="Responde preguntas frecuentes en web o WhatsApp y escala a un humano.",
            effort="M",
            impact=4,
            integrations=["Webchat", "WhatsApp", "CRM"],
            estimated_weeks=3,
            tags=["chatbot", "soporte", "web", "whatsapp", "faq", "citas", "agenda"],
        ),
        AutomationModule(
            name="Conciliacion automatica (banco vs ventas)",
            description="Compara banco, ventas y hojas de calculo para detectar errores y diferencias sin intervencion humana.",
            effort="M",
            impact=4,
            integrations=["Banco", "ERP", "Google Sheets"],
            estimated_weeks=3,
            tags=["banco", "conciliacion", "contabilidad", "tesoreria", "ventas", "sheet", "sheets", "excel"],
        ),
        AutomationModule(
            name="Sincronizacion Shopify-ERP",
            description="Actualiza inventario, pedidos y clientes entre Shopify y ERP.",
            effort="L",
            impact=4,
            integrations=["Shopify", "ERP"],
            estimated_weeks=4,
            tags=["shopify", "inventario", "erp", "stock", "pedido"],
        ),
        AutomationModule(
            name="Facturacion inteligente",
            description="Genera facturas, valida datos y envia comprobantes automaticamente.",
            effort="S",
            impact=3,
            integrations=["Facturacion", "Correo"],
            estimated_weeks=2,
            tags=["factura", "facturacion", "comprobante", "correo", "sat"],
        ),
        AutomationModule(
            name="Reportes y dashboards operativos",
            description="Convierte datos dispersos en dashboards semanales con alertas.",
            effort="S",
            impact=3,
            integrations=["BI", "Google Sheets"],
            estimated_weeks=2,
            tags=["reporte", "dashboard", "kpi", "excel", "administracion", "indicadores"],
        ),
        AutomationModule(
            name="Ruteo de tickets de soporte",
            description="Clasifica tickets y asigna SLA automaticamente.",
            effort="S",
            impact=3,
            integrations=["Helpdesk"],
            estimated_weeks=2,
            tags=["soporte", "ticket", "servicio", "sla"],
        ),
        AutomationModule(
            name="Enriquecimiento y limpieza de CRM",
            description="Depura duplicados y completa datos de clientes.",
            effort="S",
            impact=2,
            integrations=["CRM"],
            estimated_weeks=1,
            tags=["crm", "duplicado", "limpieza", "datos"],
        ),
        AutomationModule(
            name="Onboarding de personal",
            description="Automatiza checklist, accesos y capacitaciones.",
            effort="S",
            impact=2,
            integrations=["HR", "Correo"],
            estimated_weeks=1,
            tags=["onboarding", "rh", "recursos humanos", "capacitar"],
        ),
        AutomationModule(
            name="Automatizacion de correo",
            description="Clasifica, etiqueta y responde correos repetitivos.",
            effort="S",
            impact=3,
            integrations=["Correo"],
            estimated_weeks=2,
            tags=["correo", "email", "bandeja", "seguimiento"],
        ),
    ]
